<?php

namespace FrontBundle\Repository;

/**
 * PatientMeasurementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientMeasurementsRepository extends \Doctrine\ORM\EntityRepository
{
}
